# Generated by Django 4.0.5 on 2022-07-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0005_jobpostview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostview',
            old_name='JobPost',
            new_name='jobPost',
        ),
        migrations.RemoveField(
            model_name='jobpostview',
            name='user',
        ),
        migrations.AddField(
            model_name='jobpostview',
            name='userType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usertype'),
        ),
    ]
